name: create-excalidraw-flowchart
description: "Create a flowchart visualization in Excalidraw format for processes, pipelines, or logic flows"
author: "BMad"

# Config values
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/excalidraw-diagrams/create-flowchart"
shared_path: "{project-root}/_bmad/bmm/workflows/excalidraw-diagrams/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Core Excalidraw resources (universal knowledge)
helpers: "{project-root}/_bmad/core/resources/excalidraw/excalidraw-helpers.md"
json_validation: "{project-root}/_bmad/core/resources/excalidraw/validate-json-instructions.md"

# Domain-specific resources (technical diagrams)
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

# Output file (respects user's configured output_folder)
default_output_file: "{output_folder}/excalidraw-diagrams/flowchart-{timestamp}.excalidraw"

standalone: true