import DOMPurify from 'dompurify';

// <form>, <input>, and <button> are intentionally permitted: some marketing and
// transactional emails embed basic interactive forms (RSVPs, polls, feedback)
// and we want to keep rendering them. <meta> and <keygen> are not allowed —
// <meta http-equiv="refresh"> can navigate the message iframe to an attacker
// origin, and <keygen> is obsolete with no legitimate email use.
const AllowedTags = [
  '#text',
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'b',
  'bdi',
  'bdo',
  'big',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'cite',
  'center',
  'code',
  'col',
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'font',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'header',
  'hr',
  'i',
  'img',
  'input',
  'ins',
  'kbd',
  'label',
  'legend',
  'li',
  'main',
  'map',
  'mark',
  'menu',
  'menuitem',
  'meter',
  'nav',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'param',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'section',
  'select',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'strike',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'var',
  'wbr',
  'html',
];

const AllowedAttributes = [
  'abbr',
  'accept',
  'acceptcharset',
  'accesskey',
  'action',
  'align',
  'alt',
  'async',
  'autocomplete',
  'axis',
  'border',
  'background',
  'bgcolor',
  'cellpadding',
  'cellspacing',
  'char',
  'charoff',
  'charset',
  'checked',
  'classid',
  'class',
  'classname',
  'clear',
  'colspan',
  'cols',
  'color',
  'content',
  'contextmenu',
  'controls',
  'compact',
  'coords',
  'data',
  'datetime',
  'defer',
  'dir',
  'disabled',
  'download',
  'draggable',
  'enctype',
  'face',
  'form',
  'formenctype',
  'formmethod',
  'formnovalidate',
  'frame',
  'frameborder',
  'headers',
  'height',
  'hidden',
  'high',
  'href',
  'hreflang',
  'htmlfor',
  'hspace',
  'icon',
  'id',
  'label',
  'lang',
  'list',
  'loop',
  'low',
  'marginheight',
  'marginwidth',
  'max',
  'maxlength',
  'media',
  'mediagroup',
  'method',
  'min',
  'multiple',
  'muted',
  'name',
  'novalidate',
  'nowrap',
  'noshade',
  'open',
  'optimum',
  'pattern',
  'placeholder',
  'poster',
  'preload',
  'radiogroup',
  'readonly',
  'rel',
  'required',
  'role',
  'rowspan',
  'rows',
  'rules',
  'scope',
  'scoped',
  'scrolling',
  'seamless',
  'selected',
  'shape',
  'size',
  'sizes',
  'start',
  'sortable',
  'sorted',
  'span',
  'spellcheck',
  'src',
  'srcset',
  'start',
  'step',
  'style',
  'summary',
  'tabindex',
  'target',
  'title',
  'translate',
  'type',
  'usemap',
  'valign',
  'value',
  'vspace',
  'width',
  'wmode',
];

// Strip `@import` rules from <style> blocks. They reach the network even when
// the user has remote-content blocking enabled, so they're a silent open-tracking
// vector in HTML mail. We parse the CSS instead of regex-matching so both
// `@import url(...)` and the string form `@import "..."` are caught.
function stripAtImportRules(cssText: string): string {
  const ConstructedSheet = (globalThis as any).CSSStyleSheet;
  if (typeof ConstructedSheet === 'function') {
    try {
      const sheet = new ConstructedSheet();
      // replaceSync silently drops @import rules — they're not allowed in
      // constructed stylesheets — so reserialized rules are clean.
      sheet.replaceSync(cssText);
      return Array.from(sheet.cssRules as CSSRuleList)
        .map(rule => rule.cssText)
        .join('\n');
    } catch {
      // fall through to regex fallback
    }
  }
  return cssText.replace(/@import\b[^;]*;?/gi, '');
}

DOMPurify.addHook('uponSanitizeElement', (node, data) => {
  if (data.tagName !== 'style') return;
  const styleEl = node as HTMLStyleElement;
  const cssText = styleEl.textContent ?? '';
  if (!/@import/i.test(cssText)) return;
  styleEl.textContent = stripAtImportRules(cssText);
});

class SanitizeTransformer {
  async run(bodyHTML: string) {
    return DOMPurify.sanitize(bodyHTML, {
      ALLOWED_TAGS: AllowedTags,
      ALLOWED_ATTR: AllowedAttributes,
      ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|xxx):|[^a-z]|[a-z+.-]+(?:[^a-z+.\-:]|$))/i,
      KEEP_CONTENT: true,
    });
  }
}

export default new SanitizeTransformer();
