version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.9.1-stretch
    steps:
      - checkout
      - run:
          name: 'Install packages'
          command: sudo apt-get update && sudo apt-get install libsecret-1-dev libxkbfile-dev
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "app/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save Yarn Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "app/package-lock.json" }}
          paths:
            - node_modules
            - app/node_modules
      - run: npm run lint
workflows:
  version: 2
  test:
    jobs:
      - test
