#!/bin/sh
if [ "$#" -ne 1 ]; then
    logger "EdisonMail: no pid set to monitor"
    exit 1
fi
pidValue=$1
echo $pidValue | grep "[^0-9]" > /dev/null 2>&1

if [ "$?" -eq "0" ]; then
  logger "EdisonMail: pid value is not a number - $pidValue"
  exit 2
fi

if [ $pidValue -lt 1 ]; then
    logger "EdisonMail: pid value incorrect"
    exit 2
fi
logger "EdisonMail: monitoring pid $pidValue"
sleep 5
ps -p $pidValue -o command= | grep 'mailsync' > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
    logger "EdisonMail: mailsync for pid $pidValue still running, killing it now"
    kill -9 $pidValue
fi
logger "EdisonMail: mailsync for pid $pidValue have died"
exit 0


