name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            xvfb \
            dbus-x11 \
            libgbm1 \
            libnss3 \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libgtk-3-0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint:check

      - name: Run Typecheck
        run: npm run typecheck

      - name: Run tests
        run: dbus-launch --exit-with-session xvfb-run -a npm test
        timeout-minutes: 20
